run:
		javac Main.java Vetores.java algoritmos/BubbleSort.java
		java Main
compile:
		javac Main.java Vetores.java algoritmos/BubbleSort.java
#esta sem o algoritmos/InsertionSort.java

rm:
		rm -f *.class algoritmos/*.class
