run:
		java Main
compRun:
		javac Main.java Vetores.java algoritmos/BubbleSort.java algoritmos/SelectionSort.java
		java Main
compile:
		javac Main.java Vetores.java algoritmos/BubbleSort.java algoritmos/SelectionSort.java
#esta sem o algoritmos/InsertionSort.java

rm:
		rm -f *.class algoritmos/*.class
